export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM';
export const SUBMIT_MESSAGE = 'SUBMIT_MESSAGE';
export const DISPLAY_NEW_MESSAGE = 'DISPLAY_NEW_MESSAGE';
