default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  user: elharion
  password:

development:
  <<: *default
  database: chatguru_development

test:
  <<: *default
  database: chatguru_test
